package:
  name: pytraj

source:
  git_tag: test_conda
  git_url: http://github.com/pytraj/pytraj

requirements:
  build:
    - python
    - cython
  run:
    - python

about:
  home: http://github.com/pytraj/pytraj
  license: BSD
